### ISSUE TITLE
Jordán Henry Mendoza Aparicio

### ISSUE THREAD

**Issue by JordanMendoza401** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-JordanMendoza401#2]
[La lógica proposicional.pdf](https://github.com/user-attachments/files/17484039/La.logica.proposicional.pdf)

**Comment by irwingsael** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
